### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by gitamadb** [davidben/poppler#2]
Hi,
Poppler fails with a segmentation fault with som PDF documents. I've attached a sample document that fails.
[Trial.1_dp.pdf](https://github.com/davidben/poppler/files/1775742/Trial.1_dp.pdf)
Failure seems to occur when calling getColor.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2238687 in TextWord::getColor (b=<optimized out>, g=<optimized out>, r=<optimized out>, 
    this=<optimized out>) at poppler_src/poppler/TextOutputDev.h:174
174	poppler_src/poppler/TextOutputDev.h: No such file or directory.

Can you help ?

**Comment by davidben** [comment]
This isn't poppler upstream, and I'm not the maintainer. You want to file a bug at the bugzilla link here.
https://poppler.freedesktop.org/#bugzilla
